config/routes.rb
Rails.application.routes.draw do
  mount Signup::Engine, at: '/'
  ## this is frontend part
  root 'frontend#home'

  get 'notice_boards', to: 'frontend#noticeboard'

  get 'abouts', to:'frontend#about'

  get 'admission_eligibility', to: 'frontend#admission_eligibility'

  get 'tuition_fees', to: 'frontend#tuition_fees'

  get 'scholarships', to: 'frontend#scholarships'

  get 'how_to_apply', to: 'frontend#how_to_apply'

  get 'courses/:id', to: 'frontend#courses'

  get 'news' ,to:'frontend#news'

  get 'news/:id', to: 'frontend#news_details'
  
  get 'events', to:'frontend#event'

  get 'contact', to: 'frontend#contact'

  post 'contact', to: 'frontend#create_contact'
 ## this is admin part
  namespace :admin do
    get 'dashboard', to:'dashboard#index'
    resources :semesters, :departments, :abouts, :notice_boards,:admission_eligibilities,:tuition_fees_groups,:tuition_fees,
              :admission_fees_statuses,:scholarship_groups,:scholarships,:courses,:news,:icons,:events,:websites,
              :quick_links,:testimonials,:google_maps,:postal_types,:postals,:videos,:social_media,:admission_processes,
              :subjects, :mini_sliders, :sliders, :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/admin/event.rb
class Admin::Event < ApplicationRecord
  belongs_to :icon,:class_name=>'Admin::Icon', inverse_of: 'admin_events'
  validates_presence_of :name
  validates_presence_of :place
  validates_presence_of :details
  validates_uniqueness_of :name
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]
  before_action :authorized?

  layout 'college_admin'

  # GET /admin/events
  def index
    @admin_events = Admin::Event.all
  end

  # GET /admin/events/1
  def show
  end

  # GET /admin/events/new
  def new
    @admin_event = Admin::Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  def create
    @admin_event = Admin::Event.new(admin_event_params)

    if @admin_event.save
      redirect_to @admin_event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/events/1
  def update
    if @admin_event.update(admin_event_params)
      redirect_to @admin_event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/events/1
  def destroy
    @admin_event.destroy
    redirect_to admin_events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Admin::Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_event_params
      params.require(:admin_event).permit(:name, :event_date, :starting_time, :ending_time,:place, :icon_id, :details)
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for(admin_event) do |f| %>
    <% if admin_event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(admin_event.errors.count, "error") %> prohibited this admin_event from being saved:</h2>

          <ul>
            <% admin_event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :details %>
      <%= f.text_area :details %>
    </div>

    <div class="field">
      <%= f.label :event_date %>
      <%= f.date_select :event_date %>
    </div>

    <div class="field">
      <%= f.label :starting_time %>
      <%= f.text_field :starting_time %>
    </div>

    <div class="field">
      <%= f.label :ending_time %>
      <%= f.text_field :ending_time %>
    </div>
    <div class="field">
      <%= f.label :place %>
      <%= f.text_field :place %>
    </div>

    <div class="field">
      <%= f.label :icon_id %>
      <%= f.collection_select :icon_id, Admin::Icon.all, :id,:name,{ prompt:true }%>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

<%= link_to 'Show', @admin_event %> |
<%= link_to 'Back', admin_events_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th>Event date</th>
      <th>Starting time</th>
      <th>Ending time</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_events.each do |admin_event| %>
      <tr>
        <td><%= admin_event.name %></td>
        <td><%= admin_event.details.html_safe %></td>
        <td><%= admin_event.event_date %></td>
        <td><%= admin_event.starting_time %></td>
        <td><%= admin_event.ending_time %></td>
        <td><%= admin_event.icon.name %></td>
        <td><%= link_to 'Show', admin_event %></td>
        <td><%= link_to 'Edit', edit_admin_event_path(admin_event) %></td>
        <td><%= link_to 'Destroy', admin_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Event', new_admin_event_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/events/new.html.erb
<h1>New Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

<%= link_to 'Back', admin_events_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_event.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @admin_event.details.html_safe %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @admin_event.event_date %>
</p>

<p>
  <strong>Starting time:</strong>
  <%= @admin_event.starting_time %>
</p>

<p>
  <strong>Ending time:</strong>
  <%= @admin_event.ending_time %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @admin_event.icon.name %>
</p>

<%= link_to 'Edit', edit_admin_event_path(@admin_event) %> |
<%= link_to 'Back', admin_events_path %>
<%= render 'shared/extends_admin_layout' %>