config/routes.rb
Rails.application.routes.draw do
  mount Signup::Engine, at: '/'
  ## this is frontend part
  root 'frontend#home'

  get 'notice_boards', to: 'frontend#noticeboard'

  get 'abouts', to:'frontend#about'

  get 'admission_eligibility', to: 'frontend#admission_eligibility'

  get 'tuition_fees', to: 'frontend#tuition_fees'

  get 'scholarships', to: 'frontend#scholarships'

  get 'how_to_apply', to: 'frontend#how_to_apply'

  get 'courses/:id', to: 'frontend#courses'

  get 'news' ,to:'frontend#news'

  get 'news/:id', to: 'frontend#news_details'
  
  get 'events', to:'frontend#event'

  get 'contact', to: 'frontend#contact'

  post 'contact', to: 'frontend#create_contact'
 ## this is admin part
  namespace :admin do
    get 'dashboard', to:'dashboard#index'
    resources :semesters, :departments, :abouts, :notice_boards,:admission_eligibilities,:tuition_fees_groups,:tuition_fees,
              :admission_fees_statuses,:scholarship_groups,:scholarships,:courses,:news,:icons,:events,:websites,
              :quick_links,:testimonials,:google_maps,:postal_types,:postals,:videos,:social_media,:admission_processes,
              :subjects, :mini_sliders, :sliders, :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/admin/tuition_fee.rb
class Admin::TuitionFee < ApplicationRecord
  has_and_belongs_to_many :admin_admission_fees_statuses, :class_name => 'Admin::AdmissionFeesStatus', join_table: 'admin_admission_fees_statuses_admin_tuition_fees'
  belongs_to :group, :class_name => Admin::TuitionFeesGroup, inverse_of: 'tuition_fees'
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :payable
end

app/controllers/admin/tuition_fees_controller.rb
class Admin::TuitionFeesController < ApplicationController
  before_action :set_admin_tuition_fee, only: [:show, :edit, :update, :destroy]
  before_action :authorized?

  layout 'college_admin'

  # GET /admin/tuition_fees
  def index
    @admin_tuition_fees = Admin::TuitionFee.all
  end

  # GET /admin/tuition_fees/1
  def show
  end

  # GET /admin/tuition_fees/new
  def new
    @admin_tuition_fee = Admin::TuitionFee.new
  end

  # GET /admin/tuition_fees/1/edit
  def edit
  end

  # POST /admin/tuition_fees
  def create
    @admin_tuition_fee = Admin::TuitionFee.new(admin_tuition_fee_params)

    if @admin_tuition_fee.save
      redirect_to @admin_tuition_fee, notice: 'Tuition fee was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/tuition_fees/1
  def update
    if @admin_tuition_fee.update(admin_tuition_fee_params)
      redirect_to @admin_tuition_fee, notice: 'Tuition fee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/tuition_fees/1
  def destroy
    @admin_tuition_fee.destroy
    redirect_to admin_tuition_fees_url, notice: 'Tuition fee was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_tuition_fee
      @admin_tuition_fee = Admin::TuitionFee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_tuition_fee_params
      params.require(:admin_tuition_fee).permit(:name, :payable, :group_id,admin_admission_fees_status_ids: [])
    end
end

app/helpers/admin/tuition_fees_helper.rb
module Admin::TuitionFeesHelper
end

app/views/admin/tuition_fees/_form.html.erb
<%= form_for(admin_tuition_fee) do |f| %>
  <% if admin_tuition_fee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_tuition_fee.errors.count, "error") %> prohibited this admin_tuition_fee from being
        saved:</h2>

      <ul>
        <% admin_tuition_fee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :payable %>
    <%= f.number_field :payable %>
  </div>

  <div class="field">
    <%= f.label :group_id %>
    <%= f.collection_select :group_id, Admin::TuitionFeesGroup.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :admin_admission_fees_status %><br/>
    <%= f.collection_select :admin_admission_fees_status_ids, Admin::AdmissionFeesStatus.all, :id, :name, {:prompt => true}, {multiple: true} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/tuition_fees/edit.html.erb
<h1>Editing Admin Tuition Fee</h1>

<%= render 'form', admin_tuition_fee: @admin_tuition_fee %>

<%= link_to 'Show', @admin_tuition_fee %> |
<%= link_to 'Back', admin_tuition_fees_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/tuition_fees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Tuition Fees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Payable</th>
      <th>Group</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_tuition_fees.each do |admin_tuition_fee| %>
      <tr>
        <td><%= admin_tuition_fee.name %></td>
        <td><%= admin_tuition_fee.payable %></td>
        <td><%= admin_tuition_fee.group.name%></td>
        <td><%= admin_tuition_fee.admin_admission_fees_statuses.map(&:name).join(' , ') %></td>
        <td><%= link_to 'Show', admin_tuition_fee %></td>
        <td><%= link_to 'Edit', edit_admin_tuition_fee_path(admin_tuition_fee) %></td>
        <td><%= link_to 'Destroy', admin_tuition_fee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Tuition Fee', new_admin_tuition_fee_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/tuition_fees/new.html.erb
<h1>New Admin Tuition Fee</h1>

<%= render 'form', admin_tuition_fee: @admin_tuition_fee %>

<%= link_to 'Back', admin_tuition_fees_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/tuition_fees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_tuition_fee.name %>
</p>

<p>
  <strong>Payable:</strong>
  <%= @admin_tuition_fee.payable %>
</p>

<p>
  <strong>Group:</strong>
  <%= @admin_tuition_fee.group.name %>

</p>
<p>
  <strong>Status:</strong>
  <%= @admin_tuition_fee.admin_admission_fees_statuses.map{|s| s.name}.join(' , ') %>
</p>


<%= link_to 'Edit', edit_admin_tuition_fee_path(@admin_tuition_fee) %> |
<%= link_to 'Back', admin_tuition_fees_path %>
<%= render 'shared/extends_admin_layout' %>