config/routes.rb
Rails.application.routes.draw do
  mount Signup::Engine, at: '/'
  ## this is frontend part
  root 'frontend#home'

  get 'notice_boards', to: 'frontend#noticeboard'

  get 'abouts', to:'frontend#about'

  get 'admission_eligibility', to: 'frontend#admission_eligibility'

  get 'tuition_fees', to: 'frontend#tuition_fees'

  get 'scholarships', to: 'frontend#scholarships'

  get 'how_to_apply', to: 'frontend#how_to_apply'

  get 'courses/:id', to: 'frontend#courses'

  get 'news' ,to:'frontend#news'

  get 'news/:id', to: 'frontend#news_details'
  
  get 'events', to:'frontend#event'

  get 'contact', to: 'frontend#contact'

  post 'contact', to: 'frontend#create_contact'
 ## this is admin part
  namespace :admin do
    get 'dashboard', to:'dashboard#index'
    resources :semesters, :departments, :abouts, :notice_boards,:admission_eligibilities,:tuition_fees_groups,:tuition_fees,
              :admission_fees_statuses,:scholarship_groups,:scholarships,:courses,:news,:icons,:events,:websites,
              :quick_links,:testimonials,:google_maps,:postal_types,:postals,:videos,:social_media,:admission_processes,
              :subjects, :mini_sliders, :sliders, :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/admin/department.rb
class Admin::Department < ApplicationRecord
  validates :name, :short_form, presence: true
  validates :name, :short_form, uniqueness: true
  has_many :admin_notice_boards, :class_name => 'Admin::NoticeBoard'
  has_many :admin_testimonials, :class_name => 'Admin::Testimonial' , inverse_of: :department
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :set_admin_department, only: [:show, :edit, :update, :destroy]
  before_action :authorized?

  layout 'college_admin'

  # GET /admin/departments
  def index
    @admin_departments = Admin::Department.all
  end

  # GET /admin/departments/1
  def show
  end

  # GET /admin/departments/new
  def new
    @admin_department = Admin::Department.new
  end

  # GET /admin/departments/1/edit
  def edit
  end

  # POST /admin/departments
  def create
    @admin_department = Admin::Department.new(admin_department_params)

    if @admin_department.save
      redirect_to @admin_department, notice: 'Department was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/departments/1
  def update
    if @admin_department.update(admin_department_params)
      redirect_to @admin_department, notice: 'Department was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/departments/1
  def destroy
    @admin_department.destroy
    redirect_to admin_departments_url, notice: 'Department was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_department
      @admin_department = Admin::Department.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_department_params
      params.require(:admin_department).permit(:name, :short_form)
    end
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/views/admin/departments/_form.html.erb
<%= form_for(admin_department) do |f| %>
  <% if admin_department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_department.errors.count, "error") %> prohibited this admin_department from being saved:</h2>

      <ul>
      <% admin_department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :short_form %>
    <%= f.text_field :short_form %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/departments/edit.html.erb
<h1>Editing Admin Department</h1>

<%= render 'form', admin_department: @admin_department %>

<%= link_to 'Show', @admin_department %> |
<%= link_to 'Back', admin_departments_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short form</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_departments.each do |admin_department| %>
      <tr>
        <td><%= admin_department.name %></td>
        <td><%= admin_department.short_form %></td>
        <td><%= link_to 'Show', admin_department %></td>
        <td><%= link_to 'Edit', edit_admin_department_path(admin_department) %></td>
        <td><%= link_to 'Destroy', admin_department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Department', new_admin_department_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/departments/new.html.erb
<h1>New Admin Department</h1>

<%= render 'form', admin_department: @admin_department %>

<%= link_to 'Back', admin_departments_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_department.name %>
</p>

<p>
  <strong>Short form:</strong>
  <%= @admin_department.short_form %>
</p>

<%= link_to 'Edit', edit_admin_department_path(@admin_department) %> |
<%= link_to 'Back', admin_departments_path %>
<%= render 'shared/extends_admin_layout' %>