config/routes.rb
Rails.application.routes.draw do
  mount Signup::Engine, at: '/'
  ## this is frontend part
  root 'frontend#home'

  get 'notice_boards', to: 'frontend#noticeboard'

  get 'abouts', to:'frontend#about'

  get 'admission_eligibility', to: 'frontend#admission_eligibility'

  get 'tuition_fees', to: 'frontend#tuition_fees'

  get 'scholarships', to: 'frontend#scholarships'

  get 'how_to_apply', to: 'frontend#how_to_apply'

  get 'courses/:id', to: 'frontend#courses'

  get 'news' ,to:'frontend#news'

  get 'news/:id', to: 'frontend#news_details'
  
  get 'events', to:'frontend#event'

  get 'contact', to: 'frontend#contact'

  post 'contact', to: 'frontend#create_contact'
 ## this is admin part
  namespace :admin do
    get 'dashboard', to:'dashboard#index'
    resources :semesters, :departments, :abouts, :notice_boards,:admission_eligibilities,:tuition_fees_groups,:tuition_fees,
              :admission_fees_statuses,:scholarship_groups,:scholarships,:courses,:news,:icons,:events,:websites,
              :quick_links,:testimonials,:google_maps,:postal_types,:postals,:videos,:social_media,:admission_processes,
              :subjects, :mini_sliders, :sliders, :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/admin/notice_board.rb
class Admin::NoticeBoard < ApplicationRecord
  belongs_to :semester, :class_name => 'Admin::Semester'
  belongs_to :department, :class_name => 'Admin::Department'
  has_many :admin_notice_forms, :class_name => 'Admin::NoticeForm', inverse_of: :notice_board
  accepts_nested_attributes_for :admin_notice_forms, reject_if: :all_blank, allow_destroy: true
  validates :name, :notice_type, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin/notice_boards_controller.rb
class Admin::NoticeBoardsController < ApplicationController
  before_action :set_admin_notice_board, only: [:show, :edit, :update, :destroy]
  before_action :authorized?

  layout 'college_admin'

  # GET /admin/notice_boards
  def index
    @admin_notice_boards = Admin::NoticeBoard.all
  end

  # GET /admin/notice_boards/1
  def show
  end

  # GET /admin/notice_boards/new
  def new
    @admin_notice_board = Admin::NoticeBoard.new
  end

  # GET /admin/notice_boards/1/edit
  def edit
  end

  # POST /admin/notice_boards
  def create
    @admin_notice_board = Admin::NoticeBoard.new(admin_notice_board_params)

    if @admin_notice_board.save
      redirect_to @admin_notice_board, notice: 'Notice board was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/notice_boards/1
  def update
    if @admin_notice_board.update(admin_notice_board_params)
      redirect_to @admin_notice_board, notice: 'Notice board was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/notice_boards/1
  def destroy
    @admin_notice_board.destroy
    redirect_to admin_notice_boards_url, notice: 'Notice board was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_notice_board
      @admin_notice_board = Admin::NoticeBoard.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
  def admin_notice_board_params
    params.require(:admin_notice_board).permit(:name, :notice_type, :semester_id, :department_id,admin_notice_forms_attributes:[:id,:description,:background_color,:_destroy])
  end
  end

app/helpers/admin/notice_boards_helper.rb
module Admin::NoticeBoardsHelper
end

app/views/admin/notice_boards/_admin_notice_form_fields.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :background_color %>
    <%= f.radio_button :background_color, 'success' %> Pass
    <%= f.radio_button :background_color, 'danger' %> Fail
    <%= f.radio_button :background_color, 'warning' %> Referred
    <%= f.radio_button :background_color, 'info' %> Normal
    <%= link_to_remove_association 'Remove', f, class: 'form-button btn btn-default' %>
  </div>
</div>

app/views/admin/notice_boards/_form.html.erb
<%= form_for(admin_notice_board) do |f| %>
  <% if admin_notice_board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_notice_board.errors.count, "error") %> prohibited this admin_notice_board from being saved:</h2>

      <ul>
      <% admin_notice_board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :notice_type %>
      <%= f.radio_button :notice_type, 'normal' %> Normal
      <%= f.radio_button :notice_type, 'specific' %> Specific
    </div>
    <div class="field">
      <%= f.label :semester_id %>
      <% if Admin::Semester.all.blank? %>
          <%= link_to 'Add', new_admin_semester_path %>
      <% else %>
          <%= f.collection_select :semester_id, Admin::Semester.all, :id, :short_form, prompt: true %>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :department_id %>
      <% if Admin::Department.all.blank? %>
          <%= link_to 'Add', new_admin_department_path %>
      <% else %>
          <%= f.collection_select :department_id, Admin::Department.all, :id, :short_form, prompt: true %>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :notice_form %>
      <div id="admin_notice_forms">
        <%= f.fields_for :admin_notice_forms do |notice_form| %>
            <%= render 'admin_notice_form_fields', f: notice_form %>
        <% end %>
        <%= link_to_add_association 'Add Notice Form',f,:admin_notice_forms,class: 'btn btn-primary' %>
      </div>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/notice_boards/edit.html.erb
<h1>Editing Admin Notice Board</h1>

<%= render 'form', admin_notice_board: @admin_notice_board %>

<%= link_to 'Show', @admin_notice_board %> |
<%= link_to 'Back', admin_notice_boards_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/notice_boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Notice Boards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Notice type</th>
      <th>Semester</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_notice_boards.each do |admin_notice_board| %>
      <tr>
        <td><%= admin_notice_board.name %></td>
        <td><%= admin_notice_board.notice_type %></td>
        <td><%= admin_notice_board.semester.short_form %></td>
        <td><%= admin_notice_board.department.short_form %></td>
        <td><%= link_to 'Show', admin_notice_board %></td>
        <td><%= link_to 'Edit', edit_admin_notice_board_path(admin_notice_board) %></td>
        <td><%= link_to 'Destroy', admin_notice_board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Admin Notice Board', new_admin_notice_board_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/notice_boards/new.html.erb
<h1>New Admin Notice Board</h1>

<%= render 'form', admin_notice_board: @admin_notice_board %>

<%= link_to 'Back', admin_notice_boards_path %>
<%= render 'shared/extends_admin_layout' %>

app/views/admin/notice_boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_notice_board.name %>
</p>

<p>
  <strong>Notice type:</strong>
  <%= @admin_notice_board.notice_type %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @admin_notice_board.semester.short_form %>
</p>

<p>
  <strong>Department:</strong>
  <%= @admin_notice_board.department.short_form %>
</p>

<%= link_to 'Edit', edit_admin_notice_board_path(@admin_notice_board) %> |
<%= link_to 'Back', admin_notice_boards_path %>
<%= render 'shared/extends_admin_layout' %>